apiVersion: batch/v1
kind: CronJob
metadata:
  name: external-service-catalog-processor
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: processor
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: sandbox
              resources:
                requests:
                  memory: 256Mi
                limits:
                  memory: 512Mi