import-path: /etc/.credentials

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  main:
    banner-mode: off

lego:
  minio:
    url: http://minio.minio-dev.svc.cluster.local