lego:
  bricklink:
    orders:
      sync:
        scheduled:
          enabled: true
          apply: true
          fixed-delay-ms: 3600000
  fulfillment:
    sync:
      scheduled:
        enabled: true
        apply: true
        fixed-delay-ms: 3600000
