spring:
  kafka:
    bootstrap-servers: redpanda-dev-0.dev.internal.legohunter.io:31092,redpanda-dev-1.dev.internal.legohunter.io:31092,redpanda-dev-2.dev.internal.legohunter.io:31092
  config:
    import: file:${import-path}/database/database-configuration.yml, file:${import-path}/kafka/kafka-configuration.yml, , file:${import-path}/minio/minio-configuration.yml
  datasource:
    database-key-name: rasppi5-01-lego-sandbox
    hikari:
      connection-timeout: 10000
      idle-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 10000
      auto-commit: false
      login-timeout: 10000
      minimum-idle: 10
      maximum-pool-size: 10
      validation-timeout: 10000
      pool-name: rasppi5-01-mysql-jdbc-pool

lego:
  minio:
    url: https://api.minio.dev.internal.legohunter.io
  kafka:
    topic:
      bricklink-category-upload: dev-bricklink-category-upload
      bricklink-category-entry: dev-bricklink-category-entry
      bricklink-catalog-upload: dev-bricklink-catalog-upload
      bricklink-catalog-entry: dev-bricklink-catalog-entry
      rebrickable-catalog-upload: dev-rebrickable-catalog-upload
      rebrickable-catalog-entry: dev-rebrickable-catalog-entry
      rebrickable-theme-upload: dev-rebrickable-category-upload
      rebrickable-theme-entry: dev-rebrickable-category-entry
    consumer:
      group-id:
        bricklink-category-upload: dev-bricklink-category-upload-group
        bricklink-category-entry: dev-bricklink-category-entry-group
        bricklink-catalog-upload: dev-bricklink-catalog-upload-group
        bricklink-catalog-entry: dev-bricklink-catalog-entry-group
        rebrickable-catalog-upload: dev-rebrickable-catalog-upload-group
        rebrickable-catalog-entry: dev-rebrickable-catalog-entry-group
        rebrickable-theme-upload: dev-rebrickable-category-upload-group
        rebrickable-theme-entry: dev-rebrickable-category-entry-group