package io.legohunter.egress.imagehosting.preflight;

public enum ImageHostingPreflightIssueType {
    SNAPSHOT_REQUIRED,
    ITEM_INVENTORY_REQUIRED,
    ITEM_INVENTORY_ID_MISSING,
    ALBUM_TITLE_MISSING,
    ALBUM_DESCRIPTION_MISSING,
    EXTERNAL_IMAGE_ALBUM_ID_MISSING,
    PHOTO_REQUIRED,
    PHOTO_ID_MISSING,
    PHOTO_INVENTORY_MISMATCH,
    PRIMARY_PHOTO_MISSING,
    MULTIPLE_PRIMARY_PHOTOS,
    S3_LOCATION_MISSING,
    S3_OBJECT_MISSING,
    EXTERNAL_IMAGE_ID_MISSING,
    DUPLICATE_EXTERNAL_SERVICE_IMAGE_ID,
    MEMBERSHIP_EXTERNAL_IMAGE_ID_MISSING,
    MEMBERSHIP_REFERENCES_UNEXPECTED_IMAGE
}
